version: '2'
services:
  dev-image:
    image: sonic-swss
    networks:
      - default
    ports: #(HOST:CONTAINER)
      - "22:22"
    privileged: true
    volumes: #(HOST:CONTAINER)
      - ".:/sonic-swss-dev"
      - "E:\\:/mnt/e"